development:
  adapter: postgresql
  database: scaphon_data
  username:
  host: localhost

test:
  adapter: postgresql
  database: scaphon_data
  username:
  host: localhost

production:
  adapter: postgresql
  database: scaphon_data
  username:
